### PR TITLE
Fix loading ngTagsInput css and js

### PR DESCRIPTION
**Pull request by ycliae**
Deleted loading redundantly from CDN.
Include ngTagsInput css and js to gulp files building.

### CODE REVIEW

**Comment by kriswme2** [comment]
I have already did the same loll.

**Comment by ycliae** [comment]
That part is remain unchanged........ https://github.com/kriswme2/teamform-seed/blob/master/src/index.html

```

  <!-- ngTagsInput -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ng-tags-input/3.1.1/ng-tags-input.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ng-tags-input/3.1.1/ng-tags-input.bootstrap.min.css"
/>
...........


  <!-- ngTagsInput -->
  <script src="components/ng-tags-input/ng-tags-input.min.js"></script>
<link rel="stylesheet" type="text/css" href="components/ng-tags-input/ng-tags-input.min.css">
```

**Comment by kriswme2** [comment]
Oh Sorry, you're right

**Comment by kriswme2** [comment]
But you didn't use the "--save" flags when bower install

**Comment by ycliae** [comment]
ng-tags-input had been bower installed with --save in this pull request:
https://github.com/kriswme2/teamform-seed/pull/31/files

**Comment by ycliae** [comment]
I just placed the lines in the wrong place before so I did a fix with this pull request. @@

**Pull request merged**
